name = "imageaigo"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "imageaigo"
database_id = "0818a5ff-3689-41a4-92d5-ecd8a8281c3d"

# KV Namespace (ImageAiGo)
[[kv_namespaces]]
binding = "CACHE"
id = "ab48566bc17846bfb2da187751b396a4"

# AI Binding
[ai]
binding = "AI"

# R2 Storage for images
[[r2_buckets]]
binding = "R2"
bucket_name = "imageaigo"

