name = "imageaigo"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "imageaigo"
database_id = "0818a5ff-3689-41a4-92d5-ecd8a8281c3d"

# KV Namespace (ImageAiGo)
[[kv_namespaces]]
binding = "CACHE"
id = "ab48566bc17846bfb2da187751b396a4"

# AI Binding
[ai]
binding = "AI"

# Image Resizing (需要 Workers Paid Plan)
# 启用后可以使用 cf.image 选项进行高性能图片处理
# 详见: https://developers.cloudflare.com/images/image-resizing/
# [image_resizing]
# enabled = true

# R2 Storage for images
[[r2_buckets]]
binding = "R2"
bucket_name = "imageaigo"

# Queue for batch image processing
[[queues.producers]]
binding = "IMAGE_QUEUE"
queue = "image-processing-queue"

[[queues.consumers]]
queue = "image-processing-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "image-processing-dlq"

# Cron Trigger for Unsplash sync (daily at 00:00 UTC)
[triggers]
crons = ["0 0 * * *"]

# Custom Domain Routes
[[routes]]
pattern = "imageaigo.cc/*"
zone_name = "imageaigo.cc"

[[routes]]
pattern = "www.imageaigo.cc/*"
zone_name = "imageaigo.cc"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true